version: '3'

services:
  download_urls:
    image: php:7.4-cli
    volumes:
      - ./volume:/volume
    working_dir: /volume
    command:
      php download_urls.php
  zip_files:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volume:/volume
    working_dir: /volume
    command:
      php zip_files.php
