version: '3'

services:
  download_urls:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volume:/volume
    working_dir: /volume
    command:
      php download_urls.php
